version: '3.8'

services:
  app:
    build: .
    ports:
      - "8443:8443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./public/thumbnails:/app/public/thumbnails
      - ./courses.db:/app/courses.db
    restart: unless-stopped

volumes:
  mysql_data: 